### ISSUE TITLE
audit:  audit job failures due to object not found should update pres_cat status to not 'ok' and report preservation_audit error

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1184]
spawned by https://github.com/sul-dlss/preservation_catalog/issues/1177

currently, if the CatalogToMoab audit goes to examine a moab on disk, and the moab is missing, the check will error out, and we'll get a honeybadger alert because the worker blows up with an error such as:
`Errno::ENOENT: No such file or directory @ dir_initialize - /services-disk05/sdr2objects/cm/180/ts/4203/cm180ts4203`

because the exit happens in an unexpected fashion, the catalog entry for the `CompleteMoab` in question never has its `status` field updated to be something other than `ok`.  this is, of course, misleading, and makes queries by status less accurate.

instead, we should be able to handle this sort of error gracefully, we should set the status to something appropriate, and we should proactively be triggering the honeybadger alert (instead of it happening automatically because of an unhandled exception).

**Comment by ndushay** [comment]
These things should all happen:

- the audit code should trap this error case
- pres_cat status for the object should NOT be 'ok'
- preservation_audit workflow should be used to indicate error (with useful message)

**Comment by jmartin-sul** [comment]
here's a case where reporting to the argo workflow for the druid failed (from resque error queue):
```
Worker
    preservation-catalog-prod-02.stanford.edu:11999 on m2c at November 05, 2019
    Retry or Remove
Class
    MoabToCatalogJob (via ActiveJob) 
Arguments

    ---
    job_class: MoabToCatalogJob
    job_id: 50048ec6-883e-446b-ae5f-d73eab65227b
    provider_job_id: 
    queue_name: m2c
    priority: 
    arguments:
    - _aj_globalid: gid://preservation-catalog/MoabStorageRoot/9
    - zx284xc2961
    - "/services-disk10/sdr2objects/zx/284/xc/2961/zx284xc2961"
    executions: 0
    locale: en

Exception
    Dor::WorkflowException
Error
    Failed to retrieve resource: put https://sul-lyberservices-prod.stanford.edu/workflow//objects/druid:zx284xc2961/workflows/preservationAuditWF/preservation-audit (HTTP status 404)
```

very similar issue to what's described in this ticket.  we should make sure that status is getting properly set in this scenario also.  may warrant spawning its own separate ticket.

**Comment by jmartin-sul** [comment]
this is a high priority issue, because it can lead to under-counting objects that are in error when querying pres cat for object status stats.

**Comment by mjgiarlo** [comment]
The [relevant honeybadger alert](https://app.honeybadger.io/projects/54415/faults/45795762) is too old to show a backtrace, so I paired with @jmartin-sul to figure out how to reproduce this error using fixture objects. Here's what w came up with.

```ruby
druid = 'bj102hs9687'
cm = PreservedObject.find_by(druid: druid).complete_moabs.first
c2m = Audit::CatalogToMoab.new(cm, nil) # second arg not required
begin                                                                                                                                 
  c2m.send(:compare_version_and_take_action)                                                                                          
rescue => e                                                                                                                           
  puts e.backtrace                                                                                                                    
end                                                                                                                                   
   (1.4ms)  BEGIN                                                                                                                                     
   (1.3ms)  ROLLBACK                                                                                                                                  
/home/mjg/.rvm/gems/ruby-2.5.3@pres_cat/gems/moab-versioning-4.3.0/lib/moab/storage_object_validator.rb:169:in `open'                                 
/home/mjg/.rvm/gems/ruby-2.5.3@pres_cat/gems/moab-versioning-4.3.0/lib/moab/storage_object_validator.rb:169:in `entries'                              
/home/mjg/.rvm/gems/ruby-2.5.3@pres_cat/gems/moab-versioning-4.3.0/lib/moab/storage_object_validator.rb:169:in `directory_entries'                    
/home/mjg/.rvm/gems/ruby-2.5.3@pres_cat/gems/moab-versioning-4.3.0/lib/moab/storage_object_validator.rb:73:in `version_directories'                   
/home/mjg/.rvm/gems/ruby-2.5.3@pres_cat/gems/moab-versioning-4.3.0/lib/moab/storage_object_validator.rb:78:in `check_correctly_named_version_dirs'    
/home/mjg/.rvm/gems/ruby-2.5.3@pres_cat/gems/moab-versioning-4.3.0/lib/moab/storage_object_validator.rb:44:in `validation_errors'                     
/home/mjg/.rvm/gems/ruby-2.5.3@pres_cat/gems/moab-versioning-4.3.0/lib/stanford/storage_object_validator.rb:10:in `validation_errors'                 
/home/mjg/workspace/preservation_catalog/app/services/moab_validation_handler.rb:34:in `moab_validation_errors'
/home/mjg/workspace/preservation_catalog/app/services/moab_validation_handler.rb:71:in `set_status_as_seen_on_disk'
/home/mjg/workspace/preservation_catalog/app/lib/audit/catalog_to_moab.rb:73:in `block in compare_version_and_take_action'
/home/mjg/workspace/preservation_catalog/app/lib/active_record_utils.rb:10:in `block in with_transaction_and_rescue'
/home/mjg/.rvm/gems/ruby-2.5.3@pres_cat/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
/home/mjg/.rvm/gems/ruby-2.5.3@pres_cat/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/home/mjg/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/home/mjg/.rvm/gems/ruby-2.5.3@pres_cat/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
/home/mjg/.rvm/gems/ruby-2.5.3@pres_cat/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
/home/mjg/.rvm/gems/ruby-2.5.3@pres_cat/gems/activerecord-5.1.7/lib/active_record/transactions.rb:210:in `transaction'
/home/mjg/workspace/preservation_catalog/app/lib/active_record_utils.rb:10:in `with_transaction_and_rescue'
/home/mjg/workspace/preservation_catalog/app/lib/audit/catalog_to_moab.rb:63:in `compare_version_and_take_action'
```

**Comment by jmartin-sul** [comment]
i think the missing workflow issue was taken care of by #1247, #1256, #1259, #1260
