### ISSUE TITLE
Create Process for Migrating an Individual Storage Root

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1332]
This could impact planning for which roots to migrate when, or conversely, it could imply what work to do when based on ops schedule of root migration.

e.g.
- run all audits on old storage root, one at a time ~~#1330~~
    - run one of (M2C, C2M, CV), and then run (and store) full report for the storage root object statuses (esp error statuses) and then run next check, etc.)??
    - store all error info in new db field ~~#1331~~
- fix audit errors when possible (#1324, #1325), re-run audits on fixed objects.
- ops migrates data to new brick
- ~~run all audits on data on new brick #1323 ?~~
- backup prescat database
- run rake task from #1322
- trigger M2C (and CV) from prescat db for freshly migrated objects
- proceed to process for sunsetting old root #1327

This should be a checklist somewhere that we can repeat for each storage root.  A wiki page?  A google doc?  A google sheet with columns for each root??

**Comment by ndushay** [comment]
I think https://docs.google.com/spreadsheets/d/1jA9qIFuGYpn-FlR3Ko3hHGrnYgf4DkHR-_riGE7y46I/edit#gid=0 has a solid first pass at the checklist.  I will step through it on stage.

**Comment by ndushay** [comment]
See https://docs.google.com/spreadsheets/d/1jA9qIFuGYpn-FlR3Ko3hHGrnYgf4DkHR-_riGE7y46I/edit#gid=0 for a spreadsheet approach.

Also for #1378, have this template PR up:  #1384

**Comment by ndushay** [comment]
did CV run as expected?

    - logs from stage-01 show:
```
I, [2020-02-21T13:14:17.280906 #8098]  INFO -- honeybadger: ** [Honeybadger] Initializing Honeybadger Error Tracker for Ruby. Ship it! version=4.5.6 framework=rails level=1 pid=8098
I, [2020-02-21T13:14:20.494546 #8098]  INFO -- : [ActiveJob] Enqueued ChecksumValidationJob (Job ID: c52ece24-39b3-42ea-9a09-046e7eb93626) to Resque(checksum_validation) with arguments: #<GlobalID:0x000000000524e4d8 @uri=#<URI::GID gid://preservation-catalog/CompleteMoab/9137>>
I, [2020-02-21T13:14:20.499914 #8098]  INFO -- : [ActiveJob] Enqueued ChecksumValidationJob (Job ID: f5820152-d580-4ce6-8461-2970cf6a98bf) to Resque(checksum_validation) with arguments: #<GlobalID:0x0000000005204298 @uri=#<URI::GID gid://preservation-catalog/CompleteMoab/9138>>
I, [2020-02-21T13:14:20.504577 #8098]  INFO -- : [ActiveJob] Enqueued ChecksumValidationJob (Job ID: 5ecd2585-4e52-4407-bcb2-f3ee2b58a428) to Resque(checksum_validation) with arguments: #<GlobalID:0x0000000005185d80 @uri=#<URI::GID gid://preservation-catalog/CompleteMoab/9139>>
I, [2020-02-21T13:14:20.509057 #8098]  INFO -- : [ActiveJob] Enqueued ChecksumValidationJob (Job ID: 9f2b1b2e-d2b2-405c-b980-9177e2837837) to Resque(checksum_validation) with arguments: #<GlobalID:0x00000000050f54b0 @uri=#<URI::GID gid://preservation-catalog/CompleteMoab/18210>>
```

But reports showed:
```
[pres@preservation-catalog-stage-01 current]$ RAILS_ENV=production bundle exec rake prescat:reports:msr_moab_audit_errors[new_fixture_sr1,cv_after]
druids with errors details for new_fixture_sr1 written to /opt/app/pres/preservation_catalog/releases/20200221203730/log/reports/storage_new_fixture_sr1_moab_audit_errors_cv_after_2020-02-21T211523Z.csv
[pres@preservation-catalog-stage-01 current]$ cat log/reports/storage_new_fixture_sr1_moab_audit_errors_cv_after_2020-02-21T211523Z.csv
druid,previous storage root,current storage root,last checksum validation,last moab validation,status,status details
bj102hs9687,fixture_sr1,new_fixture_sr1,,,validity_unknown,
bj102hs9688,fixture_sr1,new_fixture_sr1,,,validity_unknown,
bz514sm9647,fixture_sr1,new_fixture_sr1,,,validity_unknown,
jj925bx9565,fixture_sr1,new_fixture_sr1,,,validity_unknown,
```

Then I kicked CV off manually:

logs showed:
```
I, [2020-02-21T13:19:06.107875 #9211]  INFO -- : [ActiveJob] Enqueued ChecksumValidationJob (Job ID: d19be784-28d8-4ebf-81ff-eef45fae2ba9) to Resque(checksum_validation) with arguments: #<GlobalID:0x00000000062bd0f8 @uri=#<URI::GID gid://preservation-catalog/CompleteMoab/9137>>
I, [2020-02-21T13:19:06.108625 #9211]  INFO -- : [ActiveJob] Enqueued ChecksumValidationJob (Job ID: 75ae92b4-d16e-4875-9a17-ff524274e35c) to Resque(checksum_validation) with arguments: #<GlobalID:0x00000000062972b8 @uri=#<URI::GID gid://preservation-catalog/CompleteMoab/9138>>
I, [2020-02-21T13:19:06.110124 #9211]  INFO -- : [ActiveJob] Enqueued ChecksumValidationJob (Job ID: 2296fa82-a23b-465f-bc06-c6c44329c531) to Resque(checksum_validation) with arguments: #<GlobalID:0x0000000006289398 @uri=#<URI::GID gid://preservation-catalog/CompleteMoab/9139>>
I, [2020-02-21T13:19:06.110792 #9211]  INFO -- : [ActiveJob] Enqueued ChecksumValidationJob (Job ID: 30d46c5f-9851-493d-9a78-1153eab0f2e1) to Resque(checksum_validation) with arguments: #<GlobalID:0x0000000006259c88 @uri=#<URI::GID gid://preservation-catalog/CompleteMoab/18210>>
```

error reports showed the same after:

```
[pres@preservation-catalog-stage-01 current]$ cat log/reports/storage_new_fixture_sr1_moab_audit_errors_cv_after_2020-02-21T211917Z.csv
druid,previous storage root,current storage root,last checksum validation,last moab validation,status,status details
bj102hs9687,fixture_sr1,new_fixture_sr1,,,validity_unknown,
bj102hs9688,fixture_sr1,new_fixture_sr1,,,validity_unknown,
bz514sm9647,fixture_sr1,new_fixture_sr1,,,validity_unknown,
jj925bx9565,fixture_sr1,new_fixture_sr1,,,validity_unknown,
```

then I tried C2M

```
I, [2020-02-21T13:20:23.469285 #9275]  INFO -- honeybadger: ** [Honeybadger] Initializing Honeybadger Error Tracker for Ruby. Ship it! version=4.5.6 framework=rails level=1 pid=9275
I, [2020-02-21T13:20:23.962708 #9275]  INFO -- : [ActiveJob] Enqueued CatalogToMoabJob (Job ID: 66b08bcd-5492-41a9-81e5-9ef83c0d0eff) to Resque(c2m) with arguments: #<GlobalID:0x00000000049da0b8 @uri=#<URI::GID gid://preservation-catalog/CompleteMoab/9137>>
I, [2020-02-21T13:20:23.963363 #9275]  INFO -- : [ActiveJob] Enqueued CatalogToMoabJob (Job ID: 9c7b144e-ee19-491b-a4a2-9165e0043a76) to Resque(c2m) with arguments: #<GlobalID:0x00000000049a8ec8 @uri=#<URI::GID gid://preservation-catalog/CompleteMoab/9138>>
I, [2020-02-21T13:20:23.963962 #9275]  INFO -- : [ActiveJob] Enqueued CatalogToMoabJob (Job ID: 72f32107-b9c1-48da-af72-d6e6d76571d4) to Resque(c2m) with arguments: #<GlobalID:0x00000000049a50e8 @uri=#<URI::GID gid://preservation-catalog/CompleteMoab/9139>>
I, [2020-02-21T13:20:23.964584 #9275]  INFO -- : [ActiveJob] Enqueued CatalogToMoabJob (Job ID: 9ffbefca-a592-4d57-bd92-be406df37531) to Resque(c2m) with arguments: #<GlobalID:0x0000000004988df8 @uri=#<URI::GID gid://preservation-catalog/CompleteMoab/18210>>
```

same in error reports:

```
[pres@preservation-catalog-stage-01 current]$ RAILS_ENV=production bundle exec rake prescat:reports:msr_moab_audit_errors[new_fixture_sr1,c2m_after]
druids with errors details for new_fixture_sr1 written to /opt/app/pres/preservation_catalog/releases/20200221203730/log/reports/storage_new_fixture_sr1_moab_audit_errors_c2m_after_2020-02-21T212033Z.csv
[pres@preservation-catalog-stage-01 current]$ cat log/reports/storage_new_fixture_sr1_moab_audit_errors_c2m_after_2020-02-21T212033Z.csv
druid,previous storage root,current storage root,last checksum validation,last moab validation,status,status details
bj102hs9687,fixture_sr1,new_fixture_sr1,,,validity_unknown,
bj102hs9688,fixture_sr1,new_fixture_sr1,,,validity_unknown,
bz514sm9647,fixture_sr1,new_fixture_sr1,,,validity_unknown,
jj925bx9565,fixture_sr1,new_fixture_sr1,,,validity_unknown,


then I tried M2C:

logs:

```
I, [2020-02-21T13:21:51.063652 #9424]  INFO -- : [ActiveJob] Enqueued MoabToCatalogJob (Job ID: 3d93e93d-9ada-4e02-ae43-ed65592ce45e) to Resque(m2c) with arguments: #<GlobalID:0x00000000067f2078 @uri=#<URI::GID gid://preservation-catalog/MoabStorageRoot/16>>, "bj102hs9687"
I, [2020-02-21T13:21:51.067857 #9424]  INFO -- : [ActiveJob] Enqueued MoabToCatalogJob (Job ID: a4672322-3994-4d9e-8fca-c1f3ef230df8) to Resque(m2c) with arguments: #<GlobalID:0x00000000067d29d0 @uri=#<URI::GID gid://preservation-catalog/MoabStorageRoot/16>>, "bz514sm9647"
I, [2020-02-21T13:21:51.072997 #9424]  INFO -- : [ActiveJob] Enqueued MoabToCatalogJob (Job ID: 65ade57e-2e8d-4c08-a93e-a9ea17f26651) to Resque(m2c) with arguments: #<GlobalID:0x00000000067aa6b0 @uri=#<URI::GID gid://preservation-catalog/MoabStorageRoot/16>>, "jj925bx9565"
```

and finally reports showed:

```
[pres@preservation-catalog-stage-01 current]$ RAILS_ENV=production bundle exec rake prescat:reports:msr_moab_audit_errors[new_fixture_sr1,m2c_after]
druids with errors details for new_fixture_sr1 written to /opt/app/pres/preservation_catalog/releases/20200221203730/log/reports/storage_new_fixture_sr1_moab_audit_errors_m2c_after_2020-02-21T212219Z.csv
[pres@preservation-catalog-stage-01 current]$ cart log/reports/storage_new_fixture_sr1_moab_audit_errors_m2c_after_2020-02-21T212219Z.csv
bash: cart: command not found
[pres@preservation-catalog-stage-01 current]$ cat log/reports/storage_new_fixture_sr1_moab_audit_errors_m2c_after_2020-02-21T212219Z.csv
druid,previous storage root,current storage root,last checksum validation,last moab validation,status,status details
bj102hs9687,fixture_sr1,new_fixture_sr1,,2020-02-21 21:21:52 UTC,validity_unknown,check_existence (actual location: new_fixture_sr1; actual version: 3) 
bj102hs9688,fixture_sr1,new_fixture_sr1,,,validity_unknown,
bz514sm9647,fixture_sr1,new_fixture_sr1,,2020-02-21 21:21:52 UTC,validity_unknown,check_existence (actual location: new_fixture_sr1; actual version: 3) 
jj925bx9565,fixture_sr1,new_fixture_sr1,,2020-02-21 21:21:52 UTC,validity_unknown,check_existence (actual location: new_fixture_sr1; actual version: 2) 
```

**Comment by ndushay** [comment]
here's from prescat-stage-02 log - the problem is perhaps writing to the event service.

```
[pres@preservation-catalog-stage-02 log]$ cat production.log
I, [2020-02-21T12:43:01.951123 #13166]  INFO -- : [ActiveJob] [MoabToCatalogJob] [f8ba56eb-1a93-4950-960c-dc18307dc0cf] Performing MoabToCatalogJob (Job ID: f8ba56eb-1a93-4950-960c-dc18307dc0cf) from Resque(m2c) enqueued at 2020-02-21T20:43:00Z with arguments: #<GlobalID:0x000000000473c108 @uri=#<URI::GID gid://preservation-catalog/MoabStorageRoot/8>>, "bj102hs9687"
I, [2020-02-21T12:43:01.958142 #13169]  INFO -- : [ActiveJob] [MoabToCatalogJob] [ecf96e60-4fb9-40c1-994e-7836f9c42898] Performing MoabToCatalogJob (Job ID: ecf96e60-4fb9-40c1-994e-7836f9c42898) from Resque(m2c) enqueued at 2020-02-21T20:43:00Z with arguments: #<GlobalID:0x0000000004723e50 @uri=#<URI::GID gid://preservation-catalog/MoabStorageRoot/8>>, "bz514sm9647"
I, [2020-02-21T12:43:01.958377 #13172]  INFO -- : [ActiveJob] [MoabToCatalogJob] [ea3ea9a0-c43d-44cc-b0cd-c0832cb76ba0] Performing MoabToCatalogJob (Job ID: ea3ea9a0-c43d-44cc-b0cd-c0832cb76ba0) from Resque(m2c) enqueued at 2020-02-21T20:43:00Z with arguments: #<GlobalID:0x0000000004721b28 @uri=#<URI::GID gid://preservation-catalog/MoabStorageRoot/8>>, "jj925bx9565"
E, [2020-02-21T12:43:02.070577 #13166] ERROR -- : [ActiveJob] [MoabToCatalogJob] [f8ba56eb-1a93-4950-960c-dc18307dc0cf] check_existence(bj102hs9687, fixture_sr1) unable to validate when CompleteMoab status is invalid_checksum
I, [2020-02-21T12:43:02.080109 #13172]  INFO -- : [ActiveJob] [MoabToCatalogJob] [ea3ea9a0-c43d-44cc-b0cd-c0832cb76ba0] check_existence(jj925bx9565, fixture_sr1) actual version (2) matches CompleteMoab db version
I, [2020-02-21T12:43:02.080280 #13172]  INFO -- : [ActiveJob] [MoabToCatalogJob] [ea3ea9a0-c43d-44cc-b0cd-c0832cb76ba0] Performed MoabToCatalogJob (Job ID: ea3ea9a0-c43d-44cc-b0cd-c0832cb76ba0) from Resque(m2c) in 121.72ms
I, [2020-02-21T12:43:02.081263 #13169]  INFO -- : [ActiveJob] [MoabToCatalogJob] [ecf96e60-4fb9-40c1-994e-7836f9c42898] check_existence(bz514sm9647, fixture_sr1) actual version (3) matches CompleteMoab db version
I, [2020-02-21T12:43:02.081415 #13169]  INFO -- : [ActiveJob] [MoabToCatalogJob] [ecf96e60-4fb9-40c1-994e-7836f9c42898] Performed MoabToCatalogJob (Job ID: ecf96e60-4fb9-40c1-994e-7836f9c42898) from Resque(m2c) in 123.1ms
E, [2020-02-21T12:43:02.218376 #13166] ERROR -- : [ActiveJob] [MoabToCatalogJob] [f8ba56eb-1a93-4950-960c-dc18307dc0cf] Error performing MoabToCatalogJob (Job ID: f8ba56eb-1a93-4950-960c-dc18307dc0cf) from Resque(m2c) in 266.92ms: Dor::Services::Client::UnexpectedResponse (Bad Request: 400 ({"errors":[{"status":"bad_request","detail":"#/components/schemas/Druid pattern ^druid:[b-df-hjkmnp-tv-z]{2}[0-9]{3}[b-df-hjkmnp-tv-z]{2}[0-9]{4}$ does not match value: bj102hs9687, example: druid:bc123df4567"}]}) for bj102hs9687):
/opt/app/pres/preservation_catalog/shared/bundle/ruby/2.5.0/gems/dor-services-client-4.13.0/lib/dor/services/client/versioned_service.rb:23:in `raise_exception_based_on_response!'
/opt/app/pres/preservation_catalog/shared/bundle/ruby/2.5.0/gems/dor-services-client-4.13.0/lib/dor/services/client/events.rb:30:in `create'
```

**Comment by ndushay** [comment]
I greatly prefer the github template .github/ISSUE_TEMPLATE/storage-migration-checklist.md which I used for trial run in issue #1387 over the spreadsheet version at https://docs.google.com/spreadsheets/d/1jA9qIFuGYpn-FlR3Ko3hHGrnYgf4DkHR-_riGE7y46I/edit#gid=0
