### ISSUE TITLE
Enable response validation per OpenAPI spec

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/preservation_catalog#1407]
1. Uncomment `# config.middleware.use Committee::Middleware::ResponseValidation, schema_path: 'openapi.yml'` in `config/application.rb`
1. Run the specs and watch the failures
1. Fix the failures

**Comment by aaron-collier** [comment]
This is blocked by:

https://github.com/interagent/committee/issues/257

Since some of our responses are XML and the committee gem requires responses to be JSON for validation.

**Comment by aaron-collier** [comment]
@jmartin-sul just saw this in the in-progress column, happy to pick it back up.

**Comment by justinlittman** [comment]
For what it is worth, I believe that for other apps, we only do response validation during tests.

**Comment by justinlittman** [comment]
See https://github.com/sul-dlss/dor-services-app/blob/main/config/application.rb#L57-L66

**Comment by aaron-collier** [comment]
I think this is still blocked by https://github.com/interagent/committee/issues/300

Well, that ticket is a feature request for the same issue I'm seeing working on this:

```
     Committee::InvalidResponse:
       #/components/schemas/ContentDiff expected object, but received String: "<?xml version=\"1.0\"?>\n<fileInventoryDifference objectId=\"xx123yy9999\" differenceCount=\"0\" basis=\"v0\" other=\"new-contentMetadata-all\" reportDatetime=\"2022-11-01T20:05:54Z\">\n  <fileGroupDifference groupId=\"content\" differenceCount=\"0\" identical=\"0\" copyadded=\"0\" copydeleted=\"0\" renamed=\"0\" modified=\"0\" added=\"0\" deleted=\"0\">\n    <subset change=\"identical\" count=\"0\"/>\n    <subset change=\"copyadded\" count=\"0\"/>\n    <subset change=\"copydeleted\" count=\"0\"/>\n    <subset change=\"renamed\" count=\"0\"/>\n    <subset change=\"modified\" count=\"0\"/>\n    <subset change=\"added\" count=\"0\"/>\n    <subset change=\"deleted\" count=\"0\"/>\n  </fileGroupDifference>\n</fileInventoryDifference>\n"
```

**Comment by jmartin-sul** [comment]
took another pass at this, but i think https://github.com/interagent/committee/issues/300 is still a blocker.  but https://github.com/sul-dlss/preservation_catalog/pull/2452 gets us down to 4 failing tests, see e.g. https://app.circleci.com/pipelines/github/sul-dlss/preservation_catalog/2517/workflows/b26e4aba-c0c9-4a1c-aca4-79e3e3eabd35/jobs/6881?invite=true#step-109-8883_9:

```
Failures:

  1) ObjectsController POST #content_diff when object exists when version specified returns correct Moab::FileInventoryDifference data
     Failure/Error: expect(response).to have_http_status(:ok)
       expected the response to have status code :ok (200) but it was :internal_server_error (500)
     # ./spec/requests/objects_controller_content_diff_spec.rb:45:in 'block (5 levels) in <top (required)>'
     # ./spec/support/live_s3.rb:10:in 'block (2 levels) in <top (required)>'

  2) ObjectsController POST #content_diff when object exists when druid is bare returns the Moab::FileInventoryDifference as xml
     Failure/Error: expect(response).to have_http_status(:ok)
       expected the response to have status code :ok (200) but it was :internal_server_error (500)
     # ./spec/requests/objects_controller_content_diff_spec.rb:33:in 'block (5 levels) in <top (required)>'
     # ./spec/support/live_s3.rb:10:in 'block (2 levels) in <top (required)>'

  3) ObjectsController POST #content_diff when object exists when druid is prefixed returns the Moab::FileInventoryDifference as xml
     Failure/Error: expect(response).to have_http_status(:ok)
       expected the response to have status code :ok (200) but it was :internal_server_error (500)
     # ./spec/requests/objects_controller_content_diff_spec.rb:21:in 'block (5 levels) in <top (required)>'
     # ./spec/support/live_s3.rb:10:in 'block (2 levels) in <top (required)>'

  4) ObjectsController POST #content_diff when object does not exist returns an empty Moab::FileInventoryDifference as xml
     Failure/Error: expect(response).to have_http_status(:ok)
       expected the response to have status code :ok (200) but it was :internal_server_error (500)
     # ./spec/requests/objects_controller_content_diff_spec.rb:106:in 'block (4 levels) in <top (required)>'
     # ./spec/support/live_s3.rb:10:in 'block (2 levels) in <top (required)>'
```
