### ISSUE TITLE
consider using less indirection for handling PreservedCopy status

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#373]
it is unnecessary to set pc status to e.g. `PreservedCopy.statuses[:invalid_moab]`, since `'invalid_moab'` alone will do (and we should only be able to use recognized statuses already, due to the validation configured on `PreservedCopy`).  e.g.:

```ruby
[26] pry(main)> pc = PreservedCopy.first  
  PreservedCopy Load (0.5ms)  SELECT  "preserved_copies".* FROM "preserved_copies" ORDER BY "preserved_copies"."id" ASC LIMIT $1  [["LIMIT", 1]]
=> #<PreservedCopy:0x00007ff44da3aa68
 id: 1,
 version: 3,
 last_audited: 1512509222,
 preserved_object_id: 1,
 endpoint_id: 1,
 created_at: Tue, 05 Dec 2017 21:27:02 UTC +00:00,
 updated_at: Tue, 05 Dec 2017 21:27:02 UTC +00:00,
 last_checked_on_storage: Tue, 05 Dec 2017 21:27:02 UTC +00:00,
 last_checksum_validation: nil,
 size: 2012695,
 status: "ok">
[27] pry(main)> 
...
[35] pry(main)> pc.status
=> "ok"
[36] pry(main)> 
[37] pry(main)> 
[38] pry(main)> pc.status = 'invalid_moab_'
ArgumentError: 'invalid_moab_' is not a valid status
from /Users/suntzu/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activerecord-5.1.4/lib/active_record/enum.rb:139:in `assert_valid_value'
[39] pry(main)> 
[40] pry(main)> pc.status = :invalid_moab_ 
ArgumentError: 'invalid_moab_' is not a valid status
from /Users/suntzu/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activerecord-5.1.4/lib/active_record/enum.rb:139:in `assert_valid_value'
[41] pry(main)> 
[42] pry(main)> pc.status = 7             
ArgumentError: '7' is not a valid status
from /Users/suntzu/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activerecord-5.1.4/lib/active_record/enum.rb:139:in `assert_valid_value'
[43] pry(main)> 
[44] pry(main)> 
[45] pry(main)> pc.status = 'invalid_moab' 
=> "invalid_moab"
[46] pry(main)> 
[47] pry(main)> pc.status = :invalid_moab 
=> :invalid_moab
[48] pry(main)> 
[49] pry(main)> pc.status = 1            
=> 1
[50] pry(main)> 
[51] pry(main)> pc.status    
=> "invalid_moab"
[52] pry(main)> 
[53] pry(main)> 
[54] pry(main)> pc.status = :invalid_moab
=> :invalid_moab
[55] pry(main)> 
[56] pry(main)> pc.status                
=> "invalid_moab"
[57] pry(main)> 
[58] pry(main)> 
[59] pry(main)> PreservedCopy.statuses[:ok]
=> 0
[60] pry(main)> PreservedCopy.statuses['ok']
=> 0
[61] pry(main)> 
[62] pry(main)> PreservedCopy.statuses.class.name
=> "ActiveSupport::HashWithIndifferentAccess"
```

**Comment by jmartin-sul** [comment]
if we think passing around strings like that in our code feels or looks wrong, i'd be comfortable with setting class constants in PreservedCopy to those strings (similar to what we're doing for `DEFAULT_STATUS` in #368, but without the indirection, just the string).

**Comment by jmartin-sul** [comment]
from the docs (http://edgeapi.rubyonrails.org/classes/ActiveRecord/Enum.html):
> In rare circumstances you might need to access the mapping directly. The mappings are exposed through a class method with the pluralized attribute name, which return the mapping in a HashWithIndifferentAccess:
> ```
> Conversation.statuses[:active]    # => 0
> Conversation.statuses["archived"] # => 1
> ```

which would imply (to me at least) that we're prob not supposed to rely on accessing the `statuses` array regularly.


here's a random example from another DLSS app that uses enums:
https://github.com/projectblacklight/spotlight/blob/7ab587601351e10a403b01770055c13b646b29cc/app/models/spotlight/reindexing_log_entry.rb#L5:
```ruby
enum job_status: { unstarted: 0, in_progress: 1, succeeded: 2, failed: 3 }
```

an example where we set a status (sorta contrived because it's factory girl setting up test stuff, but still):
https://github.com/projectblacklight/spotlight/blob/0a5fb660d4d8104d99e1e8b2481e0c884cff00bf/spec/factories/reindexing_log_entries.rb#L2-L7
```ruby
  factory :unstarted_reindexing_log_entry, class: Spotlight::ReindexingLogEntry do
    items_reindexed_count 15
    job_status 'unstarted'
    exhibit
    user
  end
```

and a random example of a scope with an enum:
https://github.com/projectblacklight/spotlight/blob/7ab587601351e10a403b01770055c13b646b29cc/app/models/spotlight/reindexing_log_entry.rb#L13
```ruby
scope :started_or_completed, -> { where.not(job_status: 'unstarted') }
```
