### ISSUE TITLE
Configure zip_storage on stage

### ISSUE THREAD

**Issue by atz** [sul-dlss/preservation_catalog#843]
Currently fails like:
```
Storage area not found at spec/fixtures/storage_root01/sdr2objects
/opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/moab-versioning-4.2.2/lib/moab/storage_repository.rb:73:in `block in find_storage_root'
/opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/moab-versioning-4.2.2/lib/moab/storage_repository.rb:71:in `each'
/opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/moab-versioning-4.2.2/lib/moab/storage_repository.rb:71:in `find_storage_root'
/opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/moab-versioning-4.2.2/lib/moab/storage_repository.rb:95:in `find_storage_object'
/opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/moab-versioning-4.2.2/lib/moab/storage_repository.rb:118:in `storage_object'
/opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/moab-versioning-4.2.2/lib/moab/storage_services.rb:68:in `object_version_path'
/opt/app/pres/preservation_catalog/releases/20180606001442/app/models/druid_version_zip.rb:49:in `moab_version_path'
/opt/app/pres/preservation_catalog/releases/20180606001442/app/models/druid_version_zip.rb:64:in `zip_command'
/opt/app/pres/preservation_catalog/releases/20180606001442/app/jobs/zipmaker_job.rb:7:in `zip_command'
/opt/app/pres/preservation_catalog/releases/20180606001442/app/jobs/zipmaker_job.rb:17:in `create_zip!'
/opt/app/pres/preservation_catalog/releases/20180606001442/app/jobs/zipmaker_job.rb:12:in `perform'
/opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/activejob-5.1.5/lib/active_job/execution.rb:37:in `block in perform_now'
/opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
/opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/resque-lock-1.1.0/lib/resque/plugins/lock.rb:80:in `around_perform_lock'
/opt/app/pres/preservation_catalog/releases/20180606001442/app/jobs/application_job.rb:22:in `block in <class:ApplicationJob>'
...
```

**Comment by atz** [comment]
@tallenaz, @SaravShah: did we resolve this by changing configurations?

**Comment by tallenaz** [comment]
I remember running into something like this error last week in stage, and the deployment at 202dbb1eb got us past it.
